services:
  postgres:
    image: postgres
    container_name: postgres-bd
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aO3W4S6A5D
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  prueba-tecnica:
    container_name: prueba-tecnica
    build:
      context: ./PruebaTecnica/
      dockerfile: PruebaTecnica.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
    depends_on:
      - postgres
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
